apiVersion: v1
data:
  GOOGLE_CLIENT_ID: 294472315234-m0dg2fjr0c3448gf4lph7jdk1qvu7s4a.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: ASK-FOR-SECRET
  API_SECRET_KEY: ASK-FOR-SECRET
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend--env
  name: backend--env
