apiVersion: v1
data:
  GOOGLE_CLIENT_ID: your-google-client-id
  GOOGLE_CLIENT_SECRET: your-google-client-secret
  SECRET_KEY: your-secret-key-for-session
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend--env
  name: backend--env
